disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length

opt_in_rules:
  - empty_count
  - force_unwrapping
  - closure_spacing
  - discouraged_optional_boolean
  - missing_docs

included:
  - Models
  - ViewModels
  - Views
  - Services
  - Utilities
  - Theme

identifier_name:
  min_length: 2
  excluded: [id, x, y, dx, dy]

force_unwrapping:
  severity: error

missing_docs:
  severity: warning
  included:
    - public

